"""timestamp column for favourites

Revision ID: 342c0ba3ae15
Revises: 7a4471ba2554
Create Date: 2024-12-09 23:18:17.951055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342c0ba3ae15'
down_revision: Union[str, None] = '7a4471ba2554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites', 'timestamp')
    # ### end Alembic commands ###
