"""signed_datetime column for contract

Revision ID: 7a4471ba2554
Revises: ef6c7df03d3b
Create Date: 2024-12-09 23:09:38.571315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4471ba2554'
down_revision: Union[str, None] = 'ef6c7df03d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('signed_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'signed_datetime')
    # ### end Alembic commands ###
